### ISSUE TITLE
SyntaxError in pond.tensor

### ISSUE THREAD

**Issue by BhimasenPurohit** [koenvanderveen/privateml#1]
I am trying to run, Convnet.ipynb from "image_analysis". I am getting this error,

```
File "pond/tensor.py", line 1024
    def transpose(self, *axes, reuse_mask=REUSE_MASK):
                                        ^
SyntaxError: invalid syntax
```

How to fix it.

**Comment by koenvanderveen** [comment]
Are use using python 3.6?

**Comment by BhimasenPurohit** [comment]
No,  I am using 2.7.x. But I solved this by interchanging, 2 parameters.
(self, *axes, reuse_mask=REUSE_MASK)  to (self, reuse_mask=REUSE_MASK, *axes). It executed.

But i am getting this in defining convnets.. in[6]

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-ff2a4b5ac539> in <module>()
      2     Conv2D((3, 3, 1, 32), strides=1, padding=1, filter_init=lambda shp: np.random.normal(scale=0.1, size=shp)),
      3     AveragePooling2D(pool_size=(2, 2)),
----> 4     Relu(order=3),
      5     Flatten(),
      6     Dense(10, 6272),

/home/bhimasen/Documents/privateml/image_analysis/pond/nn.pyc in __init__(self, order, domain, n)
    184         self.order = order
    185         self.coeff = NativeTensor(self.compute_coefficients_relu(order, domain, n))
--> 186         self.coeff_der = (self.coeff * NativeTensor(list(range(self.n_coeff))[::-1]))[:-1]
    187         self.initializer = None
    188         assert order > 2

AttributeError: NativeTensor instance has no attribute '__len__'


Is this because I interchanged parametrs, or other issue ?

**Comment by koenvanderveen** [comment]
I am not sure. I would recommend using python 3.6. We did not test with python 2.7

**Comment by BhimasenPurohit** [comment]
@koenvanderveen : Thank you for the reply. I tried doing complete thing in python3. I am able to run till PublicEncodedTensor. But i am getting this error in PrivateEncodedTensor.


Traceback (most recent call last):
  File "test.py", line 99, in <module>
    learning_rate=0.01
  File "/home/bhimasen/Documents/privateml/image_analysis/pond/nn.py", line 799, in fit
    y_pred = self.forward(x_batch)
  File "/home/bhimasen/Documents/privateml/image_analysis/pond/nn.py", line 741, in forward
    x = layer.forward(x)
  File "/home/bhimasen/Documents/privateml/image_analysis/pond/nn.py", line 299, in forward
    out, self.cached_x_col = conv2d(x, self.filters, self.strides, self.padding)
  File "/home/bhimasen/Documents/privateml/image_analysis/pond/nn.py", line 562, in conv2d
    W_col = y.transpose(3, 2, 0, 1).reshape(n_filters, -1)
  File "/home/bhimasen/Documents/privateml/image_analysis/pond/tensor.py", line 1033, in transpose
    return PrivateEncodedTensor.from_shares(self.shares0.transpose(*axes), self.shares1.transpose(*axes))
ValueError: axes don't match array


can you help to fix this.
